version: '2'
services:
  wallabag:
    container_name: wallabag
    hostname: wallabag
    image: wallabag/wallabag
    restart: ${RESTART_POLICY}
    environment:
      - MYSQL_ROOT_PASSWORD=${WALLABAG_DB_PASS}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=wallabag_db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=nouser
      - SYMFONY__ENV__MAILER_PASSWORD=nopassword
      - SYMFONY__ENV__FROM_EMAIL=no@email.com
      - SYMFONY__ENV__DOMAIN_NAME=${WALLABAG_DOMAIN}
    ports:
      - ${WALLABAG_HTTP_PORT}:80
    volumes:
      - ${WALLABAG_APP_VOL}:/var/www/wallabag/web/assets/images
    depends_on:
      - wallabag_db
      - wallabag_cache
  wallabag_db:
    container_name: wallabag_db
    hostname: wallabag_db
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${WALLABAG_DB_PASS}
    volumes:
      - ${WALLABAG_DB_VOLUME}:/var/lib/mysql
    restart: ${RESTART_POLICY}
  wallabag_cache:
    container_name: wallabag_cache
    hostname: wallabag_cache
    image: redis:alpine
    restart: ${RESTART_POLICY}