services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${JELLYFIN_PUID}
      - PGID=${JELLYFIN_PGID}
      - TZ=${JELLYFIN_TIME_ZONE}
    volumes:
      - ${JELLYFIN_VOL_CONFIG}:/config
      - ${JELLYFIN_MEDIA_VOLUME}:/data/media
    ports:
      - ${JELLYFIN_PORT_HTTP}:8096
      - ${JELLYFIN_PORT_HTTPS}:8920 #optional
      - ${JELLYFIN_PORT_CD_LOCAL}:7359/udp #optional
      - ${JELLYFIN_PORT_CD_DLNA}:1900/udp #optional
    restart: ${RESTART_POLICY}
