services:
    cloudflared:
      image: cloudflare/cloudflared:latest
      container_name: cloudflared
      command: tunnel --no-autoupdate run
      env_file: ${ENV_FILE_LOCATION}
      restart: ${RESTART_POLICY}