---
version: "2.1"
services:
    cloudflared:
      image: cloudflare/cloudflared:latest
      container_name: cloudflared
      command: tunnel --no-autoupdate run
      environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
      restart: ${RESTART_POLICY}